spring.application.name=heiu

# database
spring.datasource.url=jdbc:postgresql://localhost:5432/heiu
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# jwt
api.security.token.secret=ncvducfjc983j8yvh3rnfv3r01jvcijdn83rfh2839yshhfhf8dshs214yy427bdd2